name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'ClassicPress/ClassicPress'
          sparse-checkout: |
            src/wp-content/themes/the-classicpress-theme
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create artifact and bring last commit
        id: last-commit
        run : |
          cd src/wp-content/themes/
          ( echo -n "LAST_UPSTREAM_COMMIT=\""; git log -1 -- the-classicpress-theme | grep -E '\(\#[0-9]+\)' | tr -d '\n' ; echo "\""; ) >> $GITHUB_OUTPUT
          zip -r ../../../${{ github.event.repository.name }}-${{ github.ref_name }}.zip the-classicpress-theme/*
          ls ../../../
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ github.event.repository.name }}-${{ github.ref_name }}
            path: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: djn24/add-comment-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          comment: |-
            Last commit:
            ${{ steps.last-commit.outputs.LAST_UPSTREAM_COMMIT }}
